title: SemiTO-V Team PoliTO
description: A RISC-V student team at Polytechnic University of Turin specialized in processor design and low level software/firmware development
theme: just-the-docs

url: https://just-the-docs.github.io

logo: "/assets/unitrisclogo.png"

favicon_ico: "/assets/favicon.ico"

color_scheme: semito

nav_external_links:
  - title: Join
    url: https://forms.gle/nHQWzMU1bCgqwWgZ8
    hide_icon: true # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: GitHub
    url: https://github.com/unitrisc
    hide_icon: true
    opens_in_new_tab: true
  - title: Telegram
    url: https://t.me/unitrisc
    hide_icon: true
    opens_in_new_tab: true
  - title: YouTube
    url: https://www.youtube.com/@UNITRISC
    hide_icon: true
    opens_in_new_tab: true
  - title: Linkedin
    url: https://www.linkedin.com/company/unitrisc
    hide_icon: true
    opens_in_new_tab: true
aux_links:
  Website's source code: https://github.com/unitrisc/unitrisc.github.io

collections:
  guides:
    output: true
    permalink: /guides/:title

defaults:
  -
    scope:
      path: ""
      type: "guides"
    values:
      layout: about
      exclude: true
